version: '3.9'

services:

  postgres-events:
    image: postgres
    environment:
      POSTGRES_USER: admin  # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: events
    ports:
      - 5433:5432
#    volumes:
#      - ./PostgreSQL:/var/lib/postgresql/data