version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  api:
    container_name: api
    image: jiankowalski/events-backend:latest
    network_mode: host
    environment:
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  cron:
    container_name: cronjob
    image: jiankowalski/events-scheduler:latest
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:172.17.0.1"


  front:
    container_name: front
    image: jiankowalski/events-frontend:latest
    depends_on:
      - api
    ports:
      - "80:4200"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    


